#.travis.yml

language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - travis_wait 30 npm install -g firebase-tools
  - travis_wait 30 npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token 1/EVvw3QQaq1VCZvV5cMzQ6a0bVltCE9JFk_eCcSbEGDk

notifications:
  email:
    on_failure: change
    on_success: change